#!/bin/bash

# Copyright (C) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# That scripts search for AudioComms checkfiles script and runs it
#

#set -x

AUDIOCOMMS_TEST_GIT_PRJ="a/bsp/hardware/intel/PRIVATE/audiocomms_tests"
AUDIOCOMMS_CHECKFILE="code_quality/checkfiles"
CUR_PATH="."
REDIRECTION_FOUND=0

# Get quality scripts git project path
AUDIOCOMMS_TEST_GIT_PATH=$(repo list $AUDIOCOMMS_TEST_GIT_PRJ 2>/dev/null |
                           cut --delimiter ' ' --field 1)

if [ "$AUDIOCOMMS_TEST_GIT_PATH" ]
then
    # Search for the .repo directory
    while [ "$(readlink --canonicalize "$CUR_PATH")" != "/" ]
    do
        REPO_PATH=$(find -L "$CUR_PATH" -maxdepth 1 -mindepth 1 -type d -name .repo)
        if [ "$REPO_PATH" ]
        then
            REDIRECTION_FOUND=1
            # Execute AudioComms FT generic checkfiles script
            $REPO_PATH/../$AUDIOCOMMS_TEST_GIT_PATH/$AUDIOCOMMS_CHECKFILE
            break
        fi

        CUR_PATH="$CUR_PATH/.."
    done
fi

if [ $REDIRECTION_FOUND -eq 0 ]
then
    echo "Info: checkfiles redirection failed"
fi

